baseURL = 'https://yeren1613.github.io/MDQN2/'
languageCode = 'en-us'
title = '民大青年新闻网'
theme = 'ananke'
publishDir ="docs"
canonifyurls = true
[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true